name: Workflow
on: [push]
jobs:
    run-shell-command:
      runs-on: ubuntu-latest
      steps:
          - name: echo a string
            run: echo "El verdadero hombre de acción"
          - name: multiline script
            run: |
              node -v 
              npm -v
              echo "... action man"
